#include "../include/headerA3.h"

// Function to add a new car to the linked list
void addNewCar(struct car **headLL)
{
    // Step 1: Dynamically allocate memory for a new 'car' structure
    struct car *newCar = (struct car *)malloc(sizeof(struct car));

    // Step 2: Check if memory allocation was successful
    if (newCar == NULL)
    {
        // If memory allocation fails, display an error message
        printf("Memory Allocation Failed.\n");
        return; // Exit the function early to prevent further errors
    }

    // Step 3: Prompt the user to input details for the new car
    // Take input for 'model' (string) and store it in 'newCar->model'
    printf("Enter The Car Model:\n ");
    scanf("%s", newCar->model);

    // Take input for 'type' (string) and store it in 'newCar->type'
    printf("Enter The Car Type:\n ");
    scanf("%s", newCar->type);

    // Take input for 'year' (integer) and store it in 'newCar->year'
    printf("Enter Its Year Of Manufacture:\n ");
    scanf("%d", &(newCar->year));

    // Take input for 'price' (double) and store it in 'newCar->price'
    printf("Enter Its Price:\n ");
    scanf("%lf", &(newCar->price));

    // Step 4: Generate a unique 'carId' for the new car
    // The 'carId' is generated by summing the ASCII values of each character in the 'model'
    // and adding the length of the 'type' string.

    int sum = 0;                                   // Variable to hold the cumulative ASCII sum of the model string
    for (int i = 0; newCar->model[i] != '\0'; i++) // Loop through each character of 'model' until the null terminator
    {
        sum += newCar->model[i]; // Add the ASCII value of the current character to the 'sum'
    }
    newCar->carId = sum + strlen(newCar->type); // Add the length of the 'type' string to the total sum to create 'carId'

    // Step 5: Ensure the generated 'carId' is unique in the linked list
    struct car *temp = *headLL; // Temporary pointer to iterate over the linked list starting from the head

    while (temp != NULL) // Loop through the entire linked list
    {
        if (temp->carId == newCar->carId) // If a car with the same 'carId' is found
        {
            // Step 6: If 'carId' is not unique, modify it to ensure uniqueness
            // Add a random number between 1 and 999 to the existing 'carId'
            newCar->carId += rand() % 999 + 1;

            // Restart the search from the beginning of the list to ensure the new 'carId' is unique
            temp = *headLL;
            continue; // Restart the while loop to check if the new 'carId' is unique
        }
        temp = temp->nextCar; // Move to the next car in the list
    }

    // Step 7: Insert the new car at the end of the linked list
    newCar->nextCar = NULL; // Set the 'nextCar' pointer of the new car to NULL (since it will be the last car)

    if (*headLL == NULL) // Check if the linked list is empty
    {
        // If the list is empty, the new car becomes the first (head) node of the list
        *headLL = newCar;
    }
    else
    {
        // If the list is not empty, traverse the list to find the last car
        temp = *headLL;               // Start from the head of the list
        while (temp->nextCar != NULL) // Loop until the last car is found (where 'nextCar' is NULL)
        {
            temp = temp->nextCar; // Move to the next car in the list
        }
        temp->nextCar = newCar; // Link the new car at the end of the list
    }

    // Step 8: Inform the user of the successfully generated and unique 'carId'
    printf("Your Computer-Generated CarId Is %d\n", newCar->carId);
}